module.exports = ['auth',
                  'authInfo',
                  'security',
                  'secInfo',
                  'sender',
                  'senderId',
                  'receiver',
                  'receiverId',
                  'date',
                  'time',
                  'standard',
                  'version',
                  'controlNumber',
                  'ackReq',
                  'usageType',
                  'termination']