module.exports = ['pack',
                  'size',
                  'sizeUOM',
                  'test',
                  'weightQualifier',
                  'weightPerPack',
                  'weightUOM',
                  'volumePerPack',
                  'volumeMeasurementBasis',
                  'length',
                  'width',
                  'height',
                  'unitOfMeasurement',
                  'innerPack']