module.exports = ['routingSequence',
                  'idCodeQual',
                  'idCode',
                  'transportationCode',
                  'routing',
                  'orderStatusCode',
                  'locationQual',
                  'locationID',
                  'transitDirectionCode',
                  'transitDirectionQual',
                  'transitTime',
                  'serviceLevelCode',
                  'serviceLevelCode2',
                  'serviceLevelCode3']